### PR TITLE
Add DocC documentation for swiftly

### PR DESCRIPTION
**Pull request by cmcgee1024**
Create a plugin and tool that can generate a CLI reference for swiftly and generate the current latest document.

Organize the help into a GSG (Getting Started Guide), a selection of HOWTOS, and Reference topics. Write an initial version of each.

Create a Swift Package Index metadata file so that swiftly can be submitted there once the documentation is ready.

Update the RELEASING.md file to check the documentation sanity and command-line reference, regenerating it if necessary.

### CODE REVIEW

**Comment by cmcgee1024** [comment]
@swift-server-bot test this please

**Review by rauhul — COMMENTED** [review]
It would be nice to bring this plugin to argument parser for other users too!

**Review by adam-fowler — COMMENTED** [review]
Are we not able to use the standard docc plugin for generating documentation?

**Comment by cmcgee1024** [comment]
> It would be nice to bring this plugin to argument parser for other users too!

This one is highly specialized to suit swiftly at the moment. Perhaps it can be generalized to suit any project in the future.

**Comment by cmcgee1024** [comment]
> Are we not able to use the standard docc plugin for generating documentation?

The docc plugin is being used here to generate the documentation. It appears to me that this might be the first time that someone has attempted to generate a command-line reference from the argument parser to docc.

**Comment by cmcgee1024** [comment]
@swift-server-bot test this please

**Review by adam-fowler — APPROVED** [review]

**Comment by cmcgee1024** [comment]
@swift-ci test macOS

**Comment by cmcgee1024** [comment]
@swift-ci test macOS

**Pull request merged**
